version: '3.8'

services:
  app:
    image: ${{ env.DOCKER_HUB_REPOSITORY }}:v${{ needs.version-update.outputs.new_tag }}
    container_name: my_app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
